name: Deploy to Heroku - Development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.NBA_EVERYTHING_API_GH_ACTION }}

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.NBA_EVERYTHING_API_HEROKU_KEY }}
        run: |
          echo $NBA_EVERYTHING_API_HEROKU_KEY | heroku auth:token

      - name: Add Heroku remote
        run: |
          git remote add heroku https://git.heroku.com/nba-everything-api-development.git

      - name: Deploy to Heroku
        run: |
          git push heroku development:main
